import { env } from "../env.js";

interface SendReportParams {
  to: string;
  subject: string;
  reportMarkdown: string;
}

export function isEmailConfigured(): boolean {
  return !!env.resendApiKey;
}

export async function sendReportEmail(
  params: SendReportParams,
): Promise<boolean> {
  if (!env.resendApiKey) return false;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env.resendApiKey}`,
    },
    body: JSON.stringify({
      from: env.resendFrom,
      to: params.to,
      subject: params.subject,
      html: markdownToHtml(params.reportMarkdown),
    }),
  });

  if (!res.ok) {
    console.error(`Resend API error: ${res.status}`, await res.text());
    return false;
  }

  return true;
}

function markdownToHtml(md: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 640px; margin: 0 auto; padding: 24px; color: #1a1a1a; }
  h1 { font-size: 24px; } h2 { font-size: 18px; margin-top: 24px; }
  blockquote { border-left: 3px solid #3b82f6; padding-left: 12px; color: #4b5563; margin: 12px 0; }
  p { line-height: 1.6; }
</style></head>
<body>
<pre style="white-space:pre-wrap;font-family:inherit;">${escapeHtml(md)}</pre>
<hr style="margin-top:32px;border:none;border-top:1px solid #e5e7eb;">
<p style="font-size:12px;color:#9ca3af;">Generated by ProbeKit</p>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
